local TechTree = require('techtree')
table.insert(TechTree.AVAILABLE_TECH, 'ARK_ITEM_TECH')
table.insert(TechTree.AVAILABLE_TECH, 'ARK_TRAINING_TECH')

TECH.NONE.ARK_ITEM_TECH = 0
TECH.ARK_ITEM_ONE = { ARK_ITEM_TECH = 1}
TECH.NONE.ARK_TRAINING_TECH = 0
TECH.ARK_TRAINING_ONE = { ARK_TRAINING_TECH = 1}

for k,v in pairs(TUNING.PROTOTYPER_TREES) do
  v.ARK_ITEM_TECH = 0
  v.ARK_TRAINING_TECH = 0
end

TUNING.PROTOTYPER_TREES.ARK_WORKSHOP_ONE = TechTree.Create({
  ARK_ITEM_TECH = 1,
})
TUNING.PROTOTYPER_TREES.ARK_TRAINING_ROOM_ONE = TechTree.Create({
  ARK_TRAINING_TECH = 1,
})

for i, v in pairs(AllRecipes) do
	v.level.ARK_ITEM_TECH = v.level.ARK_ITEM_TECH or 0
  v.level.ARK_TRAINING_TECH = v.level.ARK_TRAINING_TECH or 0
end